---
title: "git_00"
author: "Briann Brazill"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A boat  beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —  
  
Children three that nestle near,  
Eager eye and willing ear,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  
  
Then took the other, as just as fair,  
  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  "The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
        
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

No man is an island,  
Entire of itself,  
Every man is a piece of the continent,  
A part of the main.  
If a clod be washed away by the sea,  
Europe is the less.  
As well as if a promontory were.  
As well as if a manor of thy friend's  
Or of thine own were:  
Any man's death diminishes me,  
Because I am involved in mankind,  
And therefore never send to know for whom the bell tolls;  
It tolls for thee.  